eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER
      
spring:   
  cloud:
    gateway:
      routes:
      - id: student
        uri:  lb://STUDENT
        predicates:
        - Path=/** 
