eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER
      
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      
    
      routes:
      - id: student
        uri:  lb://STUDENT
        predicates:
        - Path=/students-api-get/** 
        
      - id: student-post
        uri:  lb://STUDENT-POST
        predicates:
        - Path=/students-api-post/** 
        
       


