eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER
      
spring:   
  cloud:
    gateway:
      routes:
      - id: studentService-get
        uri:  lb://STUDENT
        predicates:
        - Path=/students-api-get/** 
        
       - id: studentService-post
        uri:  lb://STUDENT-POST
        predicates:
        - Path=/students-api-post/** 
        
       
